version: "3.4"

services:
  server:
    build: api
    env_file: api/.env
    ports:
      - 4003:4003
    environment:
      FRONTEND_LOCATION: http://localhost:5173
    depends_on:
      postgres:
        condition: service_healthy
  client:
    build:
      context: ui
      dockerfile: dev.Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./ui/src:/app/src
  postgres:
    image: postgres:15.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: work-test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    volumes:
      - ./db/pgadmin.json:/pgadmin4/servers.json
    environment:
      PGADMIN_LISTEN_PORT: 4140
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"